### ISSUE TITLE
Equipped bananium cannot be used as power

### ISSUE THREAD

**Issue by AffectedArc07** [TBartl/space-station-13-idle#212]
![image](https://user-images.githubusercontent.com/25063394/86578693-22d94f80-bf74-11ea-8a40-b405c4b13bc5.png)
If you have bananium equipped in your food slot, you cannot use it for power generation. Do not know if this is intentional or not.

**Comment by MenacingManatee** [comment]
Note that this applies to all equipped items: Grey slimes equipped as companions cannot be used to create other slimes, and base food items (i.e. potatoes) cannot be used to create more advanced food items

**Comment by MenacingManatee** [comment]
I think it has to do with how equipped items are removed from your inventory

**Comment by remona-minett** [comment]
Equipping an item removes it from your Inventory, so you will have to dequip it to return it, yeah.

**Comment by Eearslya** [comment]
This should have been fixed with #255.

**Comment by remona-minett** [comment]
This has indeed been fixed, and should be closed.

**Comment by AffectedArc07** [comment]
Aight
