### ISSUE TITLE
Quality Pasta Combining

### ISSUE THREAD

**Issue by JamieD1** [TBartl/space-station-13-idle#231]
Quality Pasta Combining was removed in https://github.com/TBartl/space-station-13-idle/pull/218

Not sure if intentional.

**Comment by Nabski89** [comment]
It was intentional. The ability to toggle off the cooking upgrade when making pasta was added in it's place.

**Comment by MenacingManatee** [comment]
Whats the purpose of the quality foods if you cant use them to create stuff then? The quality pasta makes *some* sense since you can turn the upgrades off, but some of the enemies drop quality meats which you just have to sell since it isn't worth eating and it can't be used for crafting

**Comment by PKPenguin321** [comment]
Can be closed if intentional
