### ISSUE TITLE
Inconsistent spelling of fresh sishi/shishi

### ISSUE THREAD

**Issue by Teepeepee** [TBartl/space-station-13-idle#254]
In the cooking skill tab the action you click to perform spells it as "FRESH SISHI", but the item itself spells it as "FRESH SHISHI"
I would like to know the intended spelling so that I know how to submit the grammar fix, if you want me to do it myself.

**Comment by Nabski89** [comment]
It should be SHISHI. I'll make sure that's handled in the next update.
