### ISSUE TITLE
Move speed penalty can be bypassed

### ISSUE THREAD

**Issue by Teepeepee** [TBartl/space-station-13-idle#282]
The move speed penalty you get from wearing a mech can be bypassed through leaving and reentering combat after killing an enemy instead of waiting for the move speed transition.
It is very click intensive and only saves you like, 10 seconds at most (I haven't reached a point in the game where mechs or any other wearables make you even slower than that), but it may not be intended, so I'm making you aware of it.

**Comment by Teepeepee** [comment]
Forgot to add that this is only useful for validhunting targets since the button to fight them is always visible right after you exit a fight and you don't have to scroll to their zone to fight them, so validhunting is the only possible balance concern.

**Comment by PKPenguin321** [comment]
The move delay seems to be intended for balancing AFK combats anyways, so it's likely not a major concern

**Comment by PKPenguin321** [comment]
See above, this is working as intended
