### ISSUE TITLE
Time bank bug

### ISSUE THREAD

**Issue by niceping** [TBartl/space-station-13-idle#314]
It seems like time bank is capped to 24 hours. Even with time bank itself stating that cap is 48 hours, it's still reserves up to 24 hours of offline time.

Even after waiting for a while, it still does not goes beyond 24 hours, and just displays 0:00:00, unless you will spend at least 1 second, then it will go back to 23:59:59.
![time bank 2](https://user-images.githubusercontent.com/40269243/88474452-81855e00-cf61-11ea-94cb-37be5f44f1d1.png)
![time bank 1](https://user-images.githubusercontent.com/40269243/88474459-8c3ff300-cf61-11ea-866f-73ffe0b9cbee.png)

**Comment by PatKopec** [comment]
Cannot reproduce
![chrono](https://user-images.githubusercontent.com/13424598/90459813-5b6e5c00-e0d0-11ea-95f0-bac3b69e5cb6.PNG)

**Comment by PKPenguin321** [comment]
Never seen this reproduced or reported by anyone else in years, so I'll assume this is no longer an issue
