### ISSUE TITLE
There is no benefit to using oil slimes for power instead of yellow slimes

### ISSUE THREAD

**Issue by MenacingManatee** [TBartl/space-station-13-idle#320]
At max rank of the xenobio upgrades, oil slimes provide less power per second invested than yellow slimes. Using an example where I start with only 1 ( * 32) gray slime:
32 gray slime - 5 seconds
512 orange slime - 160 seconds, 165 seconds total invested
4096 yellow slime - 2560 seconds, 2,725 seconds total invested
16384 bs slime - 20480 seconds, 23,205 seconds total invested
32768 red slime - 81920 seconds, 105,125 seconds total invested
32768 oil slime - 163840 seconds, 268,965 seconds total invested
For yellow slimes, the 4096 slimes nets you 53248 power over 20480 seconds, for 23205 seconds total invested, resulting in 2.295 power per second
For oil slimes, the 32768 slimes nets you 819,200 power over 163,840 seconds for 412325 seconds total invested, resulting in1.9 power per second

Unless my math is wrong somewhere, that's an absurdly low rate of power gain for such a late tier of power, as both are practically worthless for how much power is gained per second. The only advantage is how easy it is to obtain a large amount of the resource, and even then it is a major time sink. Oil slimes for power especially aren't unlocked until level 36 in engineering, which is quite a bit down the line considering it is worse in nearly every way compared to the much earlier obtained yellow slimes for power.

**Comment by Nabski89** [comment]
Did you count the xenobiology cape?

**Comment by MenacingManatee** [comment]
I didn't, only max level upgrades without the cape for this. I'd have to redo the math to be sure, but I think even with the cape the yellow slimes would provide more power per second invested than the oil as they jump up to x16 while oil is only at x2, and either way it is an absurd amount of time to invest for such a small amount of power gained for the time invested
