### ISSUE TITLE
New antag jobs lock you out of quite a bit of bluespace time on your first reset

### ISSUE THREAD

**Issue by PKPenguin321** [TBartl/space-station-13-idle#351]
Would have reset with 100% job completion and gotten 10 bluespace capsules from it, but the newly added antag jobs that you cannot access on your first playthrough bumped me down to 81%, locking me out of half of the available capsules. Maybe the threshold for most of them could be moved down to the 70-80% range, or you could get a bonus on your first reset.

**Comment by Nabski89** [comment]
We actually did add more breakpoints/thresholds compared to before adding the new jobs.
