### ISSUE TITLE
Validhunting tutorial causes gamebreaking runtime

### ISSUE THREAD

**Issue by PKPenguin321** [TBartl/space-station-13-idle#352]
![image](https://user-images.githubusercontent.com/8345184/89615626-de272980-d83b-11ea-946b-5f8979bb278f.png)
Popup boxes stop closing and all buttons cease functioning until you refresh the page

To reproduce:
- Open validhunting tutorial
- Click "Stats?" button
- Click "Robustness?" button
- Click "Stats?" button

Also works by starting with "Robustness?"

**Comment by PatKopec** [comment]
Should be fixed in PR #371.
