### ISSUE TITLE
Moving mouse north on elements in popup boxes closes them

### ISSUE THREAD

**Issue by PKPenguin321** [TBartl/space-station-13-idle#353]
![2020-08-06_23-31-52](https://user-images.githubusercontent.com/8345184/89616329-13804700-d83d-11ea-97fc-ab57fc689cac.gif)
Moving south, east, or west does not cause it to close. Moving north on the box but not over elements (like the empty space on the left and right edges of the popup box) does not close it. Very quickly moving your mouse north over elements while the popup box is still fading in will not close it.

Truly bizarre behavior. My best guess is that mousing over a stat causes a second popup box to appear, and when you move north you place your mouse over THAT box, which means you're no longer over the first box, which closes the first and second boxes. This is further supported by a brief flicker in the origin coordinate of my screen whenever a box closes this way, which is likely the second popup box being created without a proper origin point (as the first popup box has been closed already). If this is the case, then making it so that mousing over the second popup box does not destroy the first popup box would be the fix.

**Comment by remona-minett** [comment]
Ooh, very interesting, I thought originally that this was intentional to stop you from being able to roll over the "???" job's icon and see what it is called, but that doesn't show up anyway.

**Comment by PatKopec** [comment]
Should be fixed in #372 (for robustness badge as well)
