### ISSUE TITLE
Bartending's Chem incorrectly edits item level requirements.

### ISSUE THREAD

**Issue by remona-minett** [TBartl/space-station-13-idle#363]
During a nighttime bug report I found that the Bartending chem does two things, one which it shouldn't -
1. It *does* make every item 10 levels higher than you available. However, it also:
2. Visually reduces the level requirement for every item that is still locked, creating confusion.
```
(from ../state)

if (potionItemId == "potionBartending") {
  if (getters["level"] < action.requiredLevel) {
    action.requiredLevel -= 10;
  } else {
    action.preservePotion = true;
  }
}
```
is the culprit, I believe, as Chemistry's is *similar* in how it works but simply sets the required level to 1, thus this bug might've gone unnoticed.

Below: Bartending drinks **without** chem.
![image](https://user-images.githubusercontent.com/50187357/89770229-52b7cd80-dab3-11ea-9987-652b2d336997.png)

Below: Bartending drinks **with** chem.
![image](https://user-images.githubusercontent.com/50187357/89770249-577c8180-dab3-11ea-9388-cfc8c4b1902e.png)

This seems to be causing confusion for players who say that the item "is staying locked" due to the -10 making it *appear* as if it should also be unlocked as per the potion's effects. I believe players are anticipating a "virtual" +10 to their level rather and a -10 to the requiredLevel of items.

Not sure how to fix this which is why I'm putting this in an issue. Thanks.

**Comment by PKPenguin321** [comment]
Fixed in https://github.com/TBartl/space-station-13-idle/commit/f1844067341b70739f5e60b6b8fef926ad67379a

**Comment by remona-minett** [comment]
Thank you, I missed this. Closing
